In [2]:
# Simple 1-D array
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
# version check of numpy

print(np.__version__)

1.20.3


In [12]:
# 0-D array

arr = np.array(11)

print(arr)

11


In [10]:
# 2-D array and 3-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

print("--------------------")
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[1 2 3]
 [4 5 6]]
--------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [11]:
# Check Dimensions
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
# numpy array indexing

arr = np.array([1,3,5,7,9,11,13])
print(arr[2])
print(arr[5])

print("-----------------")

print(arr[2] + arr[3])

5
11
-----------------
12


In [30]:
# access 2-D arrays

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print("1st array 2nd element:", arr[0, 1])
print("2nd array 4th element:", arr[1, 3])

print("----------------------------")

# access 3-D arrays

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

print("----------------------------")

# Negative Indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

1st array 2nd element: 2
2nd array 4th element: 9
----------------------------
6
----------------------------
Last element from 2nd dim:  10


In [46]:
# numpy array slicing

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[2:5])
print(arr[4:])
print(arr[:4])

print(arr[-3:-1])

print(arr[1:5:2])

print(arr[::3])

[3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 4 7]


In [52]:
# slicing 2-D arrays


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2]) #from both elements return index 2
print("-----------------------------------------")
print(arr[0:2, 1:4]) #from both elements index 1 to index 4 
print("-----------------------------------------")


[7 8 9]
[3 8]
-----------------------------------------
[[2 3 4]
 [7 8 9]]
-----------------------------------------


In [64]:
# Datatype of array

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

arr = np.array(['aaaa', 'bbbb', 'cccc'])

print(arr.dtype)


print("-----------------------------------------")

# convert datatype

arr = np.array([1.1, 2.1, 3.1])

print(arr.dtype)


newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)



int64
<U4
-----------------------------------------
float64
[1 2 3]
int32


In [67]:
# copy numpy array
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 11

y = arr.copy()

print(arr)
print(x)
print(y)

[11  2  3  4  5]
[1 2 3 4 5]
[11  2  3  4  5]


In [69]:
# View numpy array
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 11

print(arr)
print(x)

[11  2  3  4  5]
[11  2  3  4  5]


In [72]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)


None
[1 2 3 4 5]


In [3]:
#numpy array shape

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [7]:
#numpy array reshape

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)

print(newarr)

print("-----------------------------------------")

newarr = arr.reshape(6, 2)

print(newarr)

print("-----------------------------------------")

newarr = arr.reshape(2, 3, 2) #3D array

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-----------------------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
-----------------------------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
#numpy array iterting

arr = np.array([1, 2, 3])

for x in arr:
  print(x)


arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

1
2
3
[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [12]:
#numpy Join 

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [16]:
#numpy array splitting

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

newarr = np.array_split(arr, 4)

print(newarr)
print(newarr[1])


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
[3 4]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [21]:
#numpy search

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

x = np.searchsorted(arr, 2)

print(x)

(array([3, 5, 6]),)
1


In [22]:
#numpy sort

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [24]:
import numpy as np
from numpy import pi
rg = np.random.default_rng(1)

A = np.arange(12).reshape(3, 4)

A = np.arange(10)

for i in A:
    print(i)

B = A.cumsum(axis=0)


print(A)
print(B)

def f(x, y):
    return 10 * x + y

b = np.fromfunction(f, (5, 4), dtype=int)

print(b[1:3:])
print(b.shape)

for i in b.flat:
    print(i)

c = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

print(c[..., 0])

a = np.floor(10 * rg.random((3, 4)))
print(a)
print(a.T)

a = np.r_[1:9, 5, 8]
print(a)

0
1
2
3
4
5
6
7
8
9
[0 1 2 3 4 5 6 7 8 9]
[ 0  1  3  6 10 15 21 28 36 45]
[[10 11 12 13]
 [20 21 22 23]]
(5, 4)
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
[[  0  10]
 [100 110]]
[[5. 9. 1. 9.]
 [3. 4. 8. 4.]
 [5. 0. 7. 5.]]
[[5. 3. 5.]
 [9. 4. 0.]
 [1. 8. 7.]
 [9. 4. 5.]]
[1 2 3 4 5 6 7 8 5 8]
